### ISSUE TITLE
Changes to P2P workshop site

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p-brazil-workshop#2]
Hey Ben,

I am making changes to the list of instructors in the website but I'm having error messages when running the Rproj file (p2p-brazil-workshop):

**Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'broom'
Quitting from lines 21-27 (p2p-brazil-workshop.Rmd) 
Error: package or namespace load failed for 'tidyverse'

Execution halted**

I already installed the broom package. What am I missing?

Thanks!
(clueless about etiquette in Github)

**Comment by diodon** [comment]
When you install the package broom in this case, see if it install properly. When not it says something like:

`broom package has non-zero exit status`

In this case the package was not installed probably because it is missing one or more dependencies.

Cheers, EKS

**Comment by eqmh** [comment]
I do get this message.

I also get all this:

_Error : .onLoad failed in loadNamespace() for 'broom', details:
  call: NULL
  error: 'import' is not an exported object from 'namespace:backports'
Error: loading failed
Execution halted
*** arch - x64
Error : .onLoad failed in loadNamespace() for 'broom', details:
  call: NULL
  error: 'import' is not an exported object from 'namespace:backports'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Enrique/Documents/R/win-library/3.3/broom'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\Enrique\Documents\R\win-library\3.3" C:\Users\Enrique\AppData\Local\Temp\RtmpSwfTH0/downloaded_packages/broom_0.5.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘broom’ had non-zero exit status_

Thanks!

**Comment by bbest** [comment]
Hola @eqmh and @diodon,

Good job using Github issues! Seems like there was a problem with your existing functions / packages (ie `backports::import()`) when running `library(tidyverse)` which apparently tries to load the R package `broom`. Are you able to run the following:

```R
tidyverse::tidyverse_update()
```

I get the following:

```
The following packages are out of date:

● broom  (0.4.4 -> 0.5.0)
● dbplyr (1.2.1 -> 1.2.2)
● haven  (1.1.1 -> 1.1.2)
● modelr (0.1.1 -> 0.1.2)
● readxl (1.0.0 -> 1.1.0)
● reprex (0.1.2 -> 0.2.0)

Start a clean R session then run:
install.packages(c("broom", "dbplyr", "haven", "modelr", "readxl", "reprex"))
```

So then I run the suggested command to update:

```R
install.packages(c("broom", "dbplyr", "haven", "modelr", "readxl", "reprex"))
```

And all is well.

I suggest restarting RStudio by double-clicking the R project file `p2p-brazil-workshop.Rproj`, clearing variables by going to the Environment pane in RStudio and clicking the button that looks like a broom (as in sweeping away the variables; not related to the R package in question), then try again. If still stuck, try using the Packages tab in Rstudio, Update all packages, restart RStudio, then try installing broom again. 

Cheers, Ben

**Comment by eqmh** [comment]
OK. This worked! 

I was able to update the list of instructors:

Now I need to push it. Working on it now.
![capture](https://user-images.githubusercontent.com/20710865/44165677-62a0a080-a097-11e8-89b7-1d1732be8a4a.JPG)

**Comment by eqmh** [comment]
Hi @bbest,

I am getting this error when commiting changes to [p2p-brazil-workshop](https://github.com/marinebon/p2p-brazil-workshop):

*** Please tell me who you are.
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Enrique@imars-7-PC.(none)')

When I run git config --global user.email "emontesh@mail.usf.edu" I get this message: 

Error: unexpected symbol in "git config"

Where is the screw-up?

**Comment by eqmh** [comment]
I think I fixed the identity problem.

The problem now is that I commit and pushed but no change to the site is happening.

**Comment by bbest** [comment]
Hi @eqmh,

I can see based on the Code > [Commits](https://github.com/marinebon/p2p-brazil-workshop/commits/master) tab that by successfully pushing commit https://github.com/marinebon/p2p-brazil-workshop/commit/86be43006b47469786ac20aafc460caca3469490, you were able to modify the `index.Rmd` file. But that is before it gets rendered to `docs/index.html`, which is the one that displays to [marinebon.github.io/p2p-brazil-workshop](https://marinebon.github.io/p2p-brazil-workshop/index.html#instructors). So try committing and pushing again for that file ;)

**Comment by eqmh** [comment]
OK. It works now. 

Check out [p2p-brazil-workshop](https://marinebon.github.io/p2p-brazil-workshop/index.html#instructors).

Closing this issue now.

**Comment by bbest** [comment]
Yay, way to go @eqmh  :checkered_flag:
