### ISSUE TITLE
setup P2P website

### ISSUE THREAD

**Issue by bbest** [marinebon/p2p-brazil-workshop#3]
Hola @eqmh,

It would be good to discuss a P2P website, not just workshop site a la #2. I can set it up so that you can edit content simply through a web browser. Then when you commit changes, Github will fire up a server (through Travis) to compile with R and output the [Rmarkdown website](https://rmarkdown.rstudio.com/lesson-13.html). Sound good?

We could discuss over WhatsApp / Google hangouts.

Cheers, Ben

PS Related to #1, I'm happy to add a link to the pictures on the P2P workshop website, say under [Agenda](https://marinebon.github.io/p2p-brazil-workshop/index.html#agenda) or [Participants](https://marinebon.github.io/p2p-brazil-workshop/participants.html)?

**Comment by eqmh** [comment]
Olá @bbest,

I agree. I am just playing a bit with the workshop website to try to train myself with these tools. 

OK. Let chat about the P2P site with @ekleins soon. How about next week?

Yes, pictures added under Participants would be good, thanks.

Cheers,
Enrique

**Comment by bbest** [comment]
Ok, let the scheduling fun begin. I could be available 7am-10pm Rio time the next couple days, and next week Monday noon LA - Friday noon LA, except busy times ([NY](https://calendar.google.com/calendar/embed?src=ben@ecoquants.com&ctz=America/New_York), [Hobart](https://calendar.google.com/calendar/embed?src=ben@ecoquants.com&ctz=Australia/Hobart)):

- Aug 16 - 17: [NY, Rio, Hobart](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20180816&p1=179&p2=396&p3=213)

- Aug 20 - 24: [NY, LA, Hobart](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20180821&p1=179&p2=396&p3=137)

**Comment by eqmh** [comment]
Hi @bbest, @diodon,

Friday 17, 7 AM is good for me. This is 8 AM Rio, and 9 PM Hobart.

Let me know if this is a good time.

**Comment by diodon** [comment]
Friday 9pm? well, anyways I don't like any of the parties I have on Friday night...

**Comment by 7yl4r** [comment]
closed by https://github.com/marinebon/p2p
